REMOTE_URL:
  - file:///opt/spaceone/inventory_v2/config/database.yaml
  - file:///opt/spaceone/inventory_v2/config/shared.yaml
  - file:///opt/spaceone/inventory_v2/config/application.yaml
GLOBAL:
  MAX_WORKERS: 1000
  DATABASES:
    default:
      db: inventory-v2
      host: mongodb
      port: 27017
      maxPoolSize: 200
      username: inventory_v2_user
      password: inventory_v2_password
  CACHES:
    default:
      backend: spaceone.core.cache.redis_cache.RedisCache
      host: redis
      port: 6379
      encoding: utf-8
      socket_timeout: 10
      socket_connect_timeout: 10
  LOG:
    loggers:
      spaceone:
        handlers:
          - console
          - file
    handlers:
      file:
        type: file
        filename: /var/log/spaceone/inventory_v2.log

  QUEUES: {}
